[package]
name = "nrf52840-hal"
version = "0.1.0"
authors = [
    "James Munns <james.munns@gmail.com>",
    "Hanno Braun <hanno@braun-robotics.com",
    "John Scarrott <johnps@outlook.com>",
    "Wez Furlong <wez@wezfurlong.org>",
]
repository = "https://github.com/nrf-rs/nrf52-hal"
description = "HAL for nRF52840 microcontrollers"

[dependencies]
bare-metal = "0.2.0"
cortex-m = "0.5.2"
cortex-m-rt = "0.5.1"
nb = "0.1.1"
nrf52840 = "0.2.0"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.nrf52-hal-common]
path = "../nrf52-hal-common"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.1"

[dependencies.void]
default-features = false
version = "1.0.2"

[features]
default = ["rt"]
rt = ["nrf52840/rt", "nrf52-hal-common/52840"]

