[workspace]
members = [
  "boards/adafruit_nrf52pro",
  "boards/nRF52-DK",
  "boards/nRF52840-DK",
  "nrf52810-hal",
  "nrf52832-hal",
  "nrf52840-hal",
  "examples/rtfm-demo",
  "examples/spi-demo",
]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false

[profile.release]
debug = true
lto = true
opt-level = "s"

