[workspace]
members = [
  "boards/adafruit_nrf52pro",
  "boards/adafruit-nrf52-bluefruit-le",
  "boards/nRF52-DK",
  "boards/nRF52840-DK",
  "boards/nRF9160-DK",
  "boards/nrf52840-mdk",
  "nrf52810-hal",
  "nrf52832-hal",
  "nrf52840-hal",
  "nrf9160-hal",
  "examples/rtfm-demo",
  "examples/spi-demo",
  "examples/twi-ssd1306",
]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false

[profile.release]
debug = true
lto = true
opt-level = "s"

