[default.probe]
protocol = "Swd"

[default.flashing]
enabled = true
halt_afterwards = false
restore_unwritten_bytes = false
do_chip_erase = false

[default.reset]
enabled = true
halt_afterwards = false

[default.general]
chip = "nRF52840_xxAA"
chip_descriptions = []
log_level = "WARN"
connect_under_reset = false

[default.rtt]
enabled = true
channels = [
]
timeout = 3000
show_timestamps = true
log_enabled = false
log_path = "./logs"

[default.gdb]
enabled = false
gdb_connection_string = "127.0.0.1:1337"
