[package]
name = "rtfm-demo"
version = "0.1.0"
authors = ["James Munns <james.munns@ferrous-systems.com>"]
edition = "2018"

[dependencies]
cortex-m-rtfm = "0.4"
panic-semihosting = "0.5"
cortex-m-semihosting = "0.3"

[dependencies.nrf52810-hal]
version = "0.8.0"
path = "../../nrf52810-hal"
optional = true

[dependencies.nrf52832-hal]
version = "0.8.0"
path = "../../nrf52832-hal"
optional = true

[dependencies.nrf52840-hal]
version = "0.8.0"
path = "../../nrf52840-hal"
optional = true

[features]
52810 = ["nrf52810-hal"]
52832 = ["nrf52832-hal"]
52840 = ["nrf52840-hal"]
default = ["52832"]
