[package]
name = "pwm-blinky-demo"
version = "0.1.0"
authors = ["Christopher Hunt <huntchr@gmail.com>"]
edition = "2018"

[dependencies]
cortex-m = { version = "0.7.3", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
rtt-target = "0.5.0"
nb = "1.0.0"

[dependencies.nrf9160-hal]
features = ["rt"]
path = "../../nrf9160-hal"
optional = true

[dependencies.nrf52832-hal]
features = ["rt"]
path = "../../nrf52832-hal"
optional = true

[dependencies.nrf52840-hal]
features = ["rt"]
path = "../../nrf52840-hal"
optional = true

[features]
9160 = ["nrf9160-hal"]
52840 = ["nrf52840-hal"]
52832 = ["nrf52832-hal"]
