[package]
name = "usb"
version = "0.1.0"
authors = ["Jonas Schievink <jonasschievink@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
cortex-m-rt = "0.6.12"
panic-semihosting = "0.5.3"
nrf52840-pac = "0.9.0"
usb-device = "0.2.7"
usbd-serial = "0.1.0"

[dependencies.nrf52840-hal]
path = "../../nrf52840-hal"
