[package]
name = "i2s-controller-demo"
version = "0.1.0"
authors = ["Henrik AlseÌr"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.6.2"
cortex-m-rtic = "0.5.3"
rtt-target = {version = "0.2.0", features = ["cortex-m"] }
nrf52840-hal = { features = ["rt"], path = "../../nrf52840-hal" }
aligned = "0.3.4"
heapless = "0.5.5"
small_morse = "0.1.0"

[dependencies.embedded-hal]
version = "0.2.3"
features = ["unproven"]
