[package]
name = "i2s-controller-demo"
version = "0.1.0"
authors = ["Henrik AlseÌr"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = { version = "0.6.14", features = ["device"] }
cortex-m-rtic = { version = "0.5.8", features = ["cortex-m-7"], default-features = false }
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
nrf52840-hal = { features = ["rt"], path = "../../nrf52840-hal" }
heapless = "0.5.5"
small_morse = "0.1.0"

[dependencies.embedded-hal]
version = "0.2.3"
features = ["unproven"]
