[package]
name = "i2s-controller-demo"
version = "0.1.0"
authors = ["Henrik AlseÃÅr"]
edition = "2018"
publish = false

[dependencies]
cortex-m = { version = "0.7.3", features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7.0", features = ["device"] }
cortex-m-rtic = { version = "1.0.0", default-features = false }
embedded-hal = "1.0.0"
systick-monotonic = "1.0.0"
rtt-target = "0.5.0"
nrf52840-hal = { features = ["rt"], path = "../../nrf52840-hal" }
heapless = "0.8.0"
small_morse = "0.1.0"
