[package]
name = "wdt-demo"
version = "0.1.0"
authors = ["James Munns <james.munns@ferrous-systems.com>"]
edition = "2018"
publish = false

[dependencies]
cortex-m = { version = "0.7.3", features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7.0", features = ["device"] }
embedded-hal = "1.0.0"
rtt-target = "0.5.0"
nrf52840-hal = { features = ["rt"], path = "../../nrf52840-hal" }
